#!/bin/sh
#SBATCH -j test-pep
#SBATCH -o test
#SBATCH -p skx-dev
#SBATCH -N 1
#SBATCH -n 48
#SBATCH -t 2:00:00        # Run time (hh:mm:ss)
#SBATCH -A TG-DMR180040

EXE='/home1/01606/qiangz/miniconda3/bin/python ' 
CMD="${EXE} test_pep.py > log_test" 
echo "===============================BEGIN=============================="
echo $CMD
eval $CMD
echo "===============================DONE==============================="
